# Setup
title: Leonardo C. Neves
description: Engineer and technology lover.
url: https://leocneves.github.io
avatar: /profile.jpg
paginate: 5
permalink: pretty
cover_image: /cover.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
linkedin: leonardo-contador-neves-096312119
twitter:
  username: leocneves
  card: summary
logo: logo.png
social:
  name: Leonardo C. Neves
  links:
    - https://twitter.com/leocneves
    - https://github.com/leocneves

google_site_verification: xxxxx
# lang: en

languages: ["en", "pt"]


sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Leonardo C. Neves
  url: https://github.com/leocneves/
  email: neves.leonardoc@gmail.com
